<?php

    $list = [
            ["label"=>"Afrikaans (South Africa)", "value"=>"AF-ZA", "data-type"=>"voice", "data-shorten"=>"af-ZA" , "data-model"=>"command_and_search"],
            ["label"=>"Albanian (Albania)", "value"=>"SQ-AL", "data-type"=>"voice", "data-shorten"=>"sq-AL" , "data-model"=>"command_and_search"],
            ["label"=>"Amharic (Ethiopia)", "value"=>"AM-ET", "data-type"=>"voice", "data-shorten"=>"am-ET" , "data-model"=>"command_and_search"],
            ["label"=>"Arabic (Algeria)", "value"=>"AR-DZ", "data-type"=>"voice", "data-shorten"=>"ar-DZ" , "data-model"=>"command_and_search"],
            ["label"=>"Arabic (Bahrain)", "value"=>"AR-BH", "data-type"=>"voice", "data-shorten"=>"ar-BH" , "data-model"=>"command_and_search"],
            ["label"=>"Arabic (Egypt)", "value"=>"AR-EG", "data-type"=>"voice", "data-shorten"=>"ar-EG" , "data-model"=>"command_and_search"],
            ["label"=>"Arabic (Iraq)", "value"=>"AR-IQ", "data-type"=>"voice", "data-shorten"=>"ar-IQ" , "data-model"=>"command_and_search"],
            ["label"=>"Arabic (Israel)", "value"=>"AR-IL", "data-type"=>"voice", "data-shorten"=>"ar-IL" , "data-model"=>"command_and_search"],
            ["label"=>"Arabic (Jordan)", "value"=>"AR-JO", "data-type"=>"voice", "data-shorten"=>"ar-JO" , "data-model"=>"command_and_search"],
            ["label"=>"Arabic (Kuwait)", "value"=>"AR-KW", "data-type"=>"voice", "data-shorten"=>"ar-KW" , "data-model"=>"command_and_search"],
            ["label"=>"Arabic (Lebanon)", "value"=>"AR-LB", "data-type"=>"voice", "data-shorten"=>"ar-LB" , "data-model"=>"command_and_search"],
            ["label"=>"Arabic (Morocco)", "value"=>"AR-MA", "data-type"=>"voice", "data-shorten"=>"ar-MA" , "data-model"=>"command_and_search"],
            ["label"=>"Arabic (Oman)", "value"=>"AR-OM", "data-type"=>"voice", "data-shorten"=>"ar-OM" , "data-model"=>"command_and_search"],
            ["label"=>"Arabic (Qatar)", "value"=>"AR-QA", "data-type"=>"voice", "data-shorten"=>"ar-QA" , "data-model"=>"command_and_search"],
            ["label"=>"Arabic (Saudi Arabia)", "value"=>"AR-SA", "data-type"=>"voice", "data-shorten"=>"ar-SA" , "data-model"=>"command_and_search"],
            ["label"=>"Arabic (State of Palestine)", "value"=>"AR-PS", "data-type"=>"voice", "data-shorten"=>"ar-PS" , "data-model"=>"command_and_search"],
            ["label"=>"Arabic (Tunisia)", "value"=>"AR-TN", "data-type"=>"voice", "data-shorten"=>"ar-TN" , "data-model"=>"command_and_search"],
            ["label"=>"Arabic (United Arab Emirates)", "value"=>"AR-AE", "data-type"=>"voice", "data-shorten"=>"ar-AE" , "data-model"=>"command_and_search"],
            ["label"=>"Arabic (Yemen)", "value"=>"AR-YE", "data-type"=>"voice", "data-shorten"=>"ar-YE" , "data-model"=>"command_and_search"],
            ["label"=>"Armenian (Armenia)", "value"=>"HY-AM", "data-type"=>"voice", "data-shorten"=>"hy-AM" , "data-model"=>"command_and_search"],
            ["label"=>"Azerbaijani (Azerbaijan)", "value"=>"AZ-AZ", "data-type"=>"voice", "data-shorten"=>"az-AZ" , "data-model"=>"command_and_search"],
            ["label"=>"Basque (Spain)", "value"=>"EU-ES", "data-type"=>"voice", "data-shorten"=>"eu-ES" , "data-model"=>"command_and_search"],
            ["label"=>"Bengali (Bangladesh)", "value"=>"BN-BD", "data-type"=>"voice", "data-shorten"=>"bn-BD" , "data-model"=>"command_and_search"],
            ["label"=>"Bengali (India)", "value"=>"BN-IN", "data-type"=>"voice", "data-shorten"=>"bn-IN" , "data-model"=>"command_and_search"],
            ["label"=>"Bosnian (Bosnia and Herzegovina)", "value"=>"BS-BA", "data-type"=>"voice", "data-shorten"=>"bs-BA" , "data-model"=>"command_and_search"],
            ["label"=>"Bulgarian (Bulgaria)", "value"=>"BG-BG", "data-type"=>"voice", "data-shorten"=>"bg-BG" , "data-model"=>"command_and_search"],
            ["label"=>"Burmese (Myanmar)", "value"=>"MY-MM", "data-type"=>"voice", "data-shorten"=>"my-MM" , "data-model"=>"command_and_search"],
            ["label"=>"Catalan (Spain)", "value"=>"CA-ES", "data-type"=>"voice", "data-shorten"=>"ca-ES" , "data-model"=>"command_and_search"],
            ["label"=>"Chinese, Cantonese (Traditional Hong Kong)", "value"=>"YUE-HANT-HK", "data-type"=>"voice", "data-shorten"=>"yue-Hant-HK" , "data-model"=>"command_and_search"],
            ["label"=>"Chinese, Mandarin (Simplified, China)", "value"=>"ZH", "data-type"=>"voice", "data-shorten"=>"zh" , "data-model"=>"command_and_search"],
            ["label"=>"Chinese, Mandarin (Traditional, Taiwan)", "value"=>"ZH-TW", "data-type"=>"voice", "data-shorten"=>"zh-TW" , "data-model"=>"command_and_search"],
            ["label"=>"Croatian (Croatia)", "value"=>"HR-HR", "data-type"=>"voice", "data-shorten"=>"hr-HR" , "data-model"=>"command_and_search"],
            ["label"=>"Czech (Czech Republic)", "value"=>"CS-CZ", "data-type"=>"voice", "data-shorten"=>"cs-CZ" , "data-model"=>"command_and_search"],
            ["label"=>"Danish (Denmark)", "value"=>"DA-DK", "data-type"=>"voice", "data-shorten"=>"da-DK" , "data-model"=>"command_and_search"],
            ["label"=>"Dutch (Belgium)", "value"=>"NL-BE", "data-type"=>"voice", "data-shorten"=>"nl-BE" , "data-model"=>"command_and_search"],
            ["label"=>"Dutch (Netherlands)", "value"=>"NL-NL", "data-type"=>"voice", "data-shorten"=>"nl-NL" , "data-model"=>"command_and_search"],
            ["label"=>"English (Australia)", "value"=>"EN-AU", "data-type"=>"voice", "data-shorten"=>"en-AU" , "data-model"=>"command_and_search"],
            ["label"=>"English (Canada)", "value"=>"EN-CA", "data-type"=>"voice", "data-shorten"=>"en-CA" , "data-model"=>"command_and_search"],
            ["label"=>"English (Ghana)", "value"=>"EN-GH", "data-type"=>"voice", "data-shorten"=>"en-GH" , "data-model"=>"command_and_search"],
            ["label"=>"English (Hong Kong)", "value"=>"EN-HK", "data-type"=>"voice", "data-shorten"=>"en-HK" , "data-model"=>"command_and_search"],
            ["label"=>"English (India)", "value"=>"EN-IN", "data-type"=>"voice", "data-shorten"=>"en-IN" , "data-model"=>"command_and_search"],
            ["label"=>"English (Ireland)", "value"=>"EN-IE", "data-type"=>"voice", "data-shorten"=>"en-IE" , "data-model"=>"command_and_search"],
            ["label"=>"English (Kenya)", "value"=>"EN-KE", "data-type"=>"voice", "data-shorten"=>"en-KE" , "data-model"=>"command_and_search"],
            ["label"=>"English (New Zealand)", "value"=>"EN-NZ", "data-type"=>"voice", "data-shorten"=>"en-NZ" , "data-model"=>"command_and_search"],
            ["label"=>"English (Nigeria)", "value"=>"EN-NG", "data-type"=>"voice", "data-shorten"=>"en-NG" , "data-model"=>"command_and_search"],
            ["label"=>"English (Pakistan)", "value"=>"EN-PK", "data-type"=>"voice", "data-shorten"=>"en-PK" , "data-model"=>"command_and_search"],
            ["label"=>"English (Philippines)", "value"=>"EN-PH", "data-type"=>"voice", "data-shorten"=>"en-PH" , "data-model"=>"command_and_search"],
            ["label"=>"English (Singapore)", "value"=>"EN-SG", "data-type"=>"voice", "data-shorten"=>"en-SG" , "data-model"=>"command_and_search"],
            ["label"=>"English (South Africa)", "value"=>"EN-ZA", "data-type"=>"voice", "data-shorten"=>"en-ZA" , "data-model"=>"command_and_search"],
            ["label"=>"English (Tanzania)", "value"=>"EN-TZ", "data-type"=>"voice", "data-shorten"=>"en-TZ" , "data-model"=>"command_and_search"],
            ["label"=>"English (United Kingdom)", "value"=>"EN-GB", "data-type"=>"voice", "data-shorten"=>"en-GB" , "data-model"=>"command_and_search"],
            ["label"=>"English (United Kingdom)", "value"=>"EN-GB", "data-type"=>"voice", "data-shorten"=>"en-GB" , "data-model"=>"command_and_search"],
            ["label"=>"English (United States)", "value"=>"EN-US", "data-type"=>"voice", "data-shorten"=>"en-US" , "data-model"=>"command_and_search"],
            ["label"=>"Estonian (Estonia)", "value"=>"ET-EE", "data-type"=>"voice", "data-shorten"=>"et-EE" , "data-model"=>"command_and_search"],
            ["label"=>"Filipino (Philippines)", "value"=>"FIL-PH", "data-type"=>"voice", "data-shorten"=>"fil-PH" , "data-model"=>"command_and_search"],
            ["label"=>"Finnish (Finland)", "value"=>"FI-FI", "data-type"=>"voice", "data-shorten"=>"fi-FI" , "data-model"=>"command_and_search"],
            ["label"=>"French (Belgium)", "value"=>"FR-BE", "data-type"=>"voice", "data-shorten"=>"fr-BE" , "data-model"=>"command_and_search"],
            ["label"=>"French (Canada)", "value"=>"FR-CA", "data-type"=>"voice", "data-shorten"=>"fr-CA" , "data-model"=>"command_and_search"],
            ["label"=>"French (France)", "value"=>"FR-FR", "data-type"=>"voice", "data-shorten"=>"fr-FR" , "data-model"=>"command_and_search"],
            ["label"=>"French (Switzerland)", "value"=>"FR-CH", "data-type"=>"voice", "data-shorten"=>"fr-CH" , "data-model"=>"command_and_search"],
            ["label"=>"Galician (Spain)", "value"=>"GL-ES", "data-type"=>"voice", "data-shorten"=>"gl-ES" , "data-model"=>"command_and_search"],
            ["label"=>"Georgian (Georgia)", "value"=>"KA-GE", "data-type"=>"voice", "data-shorten"=>"ka-GE" , "data-model"=>"command_and_search"],
            ["label"=>"German (Austria)", "value"=>"DE-AT", "data-type"=>"voice", "data-shorten"=>"de-AT" , "data-model"=>"command_and_search"],
            ["label"=>"German (Germany)", "value"=>"DE-DE", "data-type"=>"voice", "data-shorten"=>"de-DE" , "data-model"=>"command_and_search"],
            ["label"=>"German (Switzerland)", "value"=>"DE-CH", "data-type"=>"voice", "data-shorten"=>"de-CH" , "data-model"=>"command_and_search"],
            ["label"=>"Greek (Greece)", "value"=>"EL-GR", "data-type"=>"voice", "data-shorten"=>"el-GR" , "data-model"=>"command_and_search"],
            ["label"=>"Gujarati (India)", "value"=>"GU-IN", "data-type"=>"voice", "data-shorten"=>"gu-IN" , "data-model"=>"command_and_search"],
            ["label"=>"Hebrew (Israel)", "value"=>"IW-IL", "data-type"=>"voice", "data-shorten"=>"iw-IL" , "data-model"=>"command_and_search"],
            ["label"=>"Hindi (India)", "value"=>"HI-IN", "data-type"=>"voice", "data-shorten"=>"hi-IN" , "data-model"=>"command_and_search"],
            ["label"=>"Hungarian (Hungary)", "value"=>"HU-HU", "data-type"=>"voice", "data-shorten"=>"hu-HU" , "data-model"=>"command_and_search"],
            ["label"=>"Icelandic (Iceland)", "value"=>"IS-IS", "data-type"=>"voice", "data-shorten"=>"is-IS" , "data-model"=>"command_and_search"],
            ["label"=>"Indonesian (Indonesia)", "value"=>"ID-ID", "data-type"=>"voice", "data-shorten"=>"id-ID" , "data-model"=>"command_and_search"],
            ["label"=>"Italian (Italy)", "value"=>"IT-IT", "data-type"=>"voice", "data-shorten"=>"it-IT" , "data-model"=>"command_and_search"],
            ["label"=>"Italian (Switzerland)", "value"=>"IT-CH", "data-type"=>"voice", "data-shorten"=>"it-CH" , "data-model"=>"command_and_search"],
            ["label"=>"Japanese (Japan)", "value"=>"JA-JP", "data-type"=>"voice", "data-shorten"=>"ja-JP" , "data-model"=>"command_and_search"],
            ["label"=>"Javanese (Indonesia)", "value"=>"JV-ID", "data-type"=>"voice", "data-shorten"=>"jv-ID" , "data-model"=>"command_and_search"],
            ["label"=>"Kannada (India)", "value"=>"KN-IN", "data-type"=>"voice", "data-shorten"=>"kn-IN" , "data-model"=>"command_and_search"],
            ["label"=>"Kazakh (Kazakhstan)", "value"=>"KK-KZ", "data-type"=>"voice", "data-shorten"=>"kk-KZ" , "data-model"=>"command_and_search"],
            ["label"=>"Khmer (Cambodia)", "value"=>"KM-KH", "data-type"=>"voice", "data-shorten"=>"km-KH" , "data-model"=>"command_and_search"],
            ["label"=>"Korean (South Korea)", "value"=>"KO-KR", "data-type"=>"voice", "data-shorten"=>"ko-KR" , "data-model"=>"command_and_search"],
            ["label"=>"Lao (Laos)", "value"=>"LO-LA", "data-type"=>"voice", "data-shorten"=>"lo-LA" , "data-model"=>"command_and_search"],
            ["label"=>"Latvian (Latvia)", "value"=>"LV-LV", "data-type"=>"voice", "data-shorten"=>"lv-LV" , "data-model"=>"command_and_search"],
            ["label"=>"Lithuanian (Lithuania)", "value"=>"LT-LT", "data-type"=>"voice", "data-shorten"=>"lt-LT" , "data-model"=>"command_and_search"],
            ["label"=>"Macedonian (North Macedonia)", "value"=>"MK-MK", "data-type"=>"voice", "data-shorten"=>"mk-MK" , "data-model"=>"command_and_search"],
            ["label"=>"Malay (Malaysia)", "value"=>"MS-MY", "data-type"=>"voice", "data-shorten"=>"ms-MY" , "data-model"=>"command_and_search"],
            ["label"=>"Malayalam (India)", "value"=>"ML-IN", "data-type"=>"voice", "data-shorten"=>"ml-IN" , "data-model"=>"command_and_search"],
            ["label"=>"Marathi (India)", "value"=>"MR-IN", "data-type"=>"voice", "data-shorten"=>"mr-IN" , "data-model"=>"command_and_search"],
            ["label"=>"Mongolian (Mongolia)", "value"=>"MN-MN", "data-type"=>"voice", "data-shorten"=>"mn-MN" , "data-model"=>"command_and_search"],
            ["label"=>"Nepali (Nepal)", "value"=>"NE-NP", "data-type"=>"voice", "data-shorten"=>"ne-NP" , "data-model"=>"command_and_search"],
            ["label"=>"Norwegian Bokmål (Norway)", "value"=>"NO-NO", "data-type"=>"voice", "data-shorten"=>"no-NO" , "data-model"=>"command_and_search"],
            ["label"=>"Persian (Iran)", "value"=>"FA-IR", "data-type"=>"voice", "data-shorten"=>"fa-IR" , "data-model"=>"command_and_search"],
            ["label"=>"Polish (Poland)", "value"=>"PL-PL", "data-type"=>"voice", "data-shorten"=>"pl-PL" , "data-model"=>"command_and_search"],
            ["label"=>"Portuguese (Brazil)", "value"=>"PT-BR", "data-type"=>"voice", "data-shorten"=>"pt-BR" , "data-model"=>"command_and_search"],
            ["label"=>"Portuguese (Portugal)", "value"=>"PT-PT", "data-type"=>"voice", "data-shorten"=>"pt-PT" , "data-model"=>"command_and_search"],
            ["label"=>"Punjabi (Gurmukhi India)", "value"=>"PA-GURU-IN", "data-type"=>"voice", "data-shorten"=>"pa-Guru-IN" , "data-model"=>"command_and_search"],
            ["label"=>"Romanian (Romania)", "value"=>"RO-RO", "data-type"=>"voice", "data-shorten"=>"ro-RO" , "data-model"=>"command_and_search"],
            ["label"=>"Russian (Russia)", "value"=>"RU-RU", "data-type"=>"voice", "data-shorten"=>"ru-RU" , "data-model"=>"command_and_search"],
            ["label"=>"Serbian (Serbia)", "value"=>"SR-RS", "data-type"=>"voice", "data-shorten"=>"sr-RS" , "data-model"=>"command_and_search"],
            ["label"=>"Sinhala (Sri Lanka)", "value"=>"SI-LK", "data-type"=>"voice", "data-shorten"=>"si-LK" , "data-model"=>"command_and_search"],
            ["label"=>"Slovak (Slovakia)", "value"=>"SK-SK", "data-type"=>"voice", "data-shorten"=>"sk-SK" , "data-model"=>"command_and_search"],
            ["label"=>"Slovenian (Slovenia)", "value"=>"SL-SI", "data-type"=>"voice", "data-shorten"=>"sl-SI" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (Argentina)", "value"=>"ES-AR", "data-type"=>"voice", "data-shorten"=>"es-AR" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (Bolivia)", "value"=>"ES-BO", "data-type"=>"voice", "data-shorten"=>"es-BO" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (Chile)", "value"=>"ES-CL", "data-type"=>"voice", "data-shorten"=>"es-CL" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (Colombia)", "value"=>"ES-CO", "data-type"=>"voice", "data-shorten"=>"es-CO" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (Costa Rica)", "value"=>"ES-CR", "data-type"=>"voice", "data-shorten"=>"es-CR" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (Dominican Republic)", "value"=>"ES-DO", "data-type"=>"voice", "data-shorten"=>"es-DO" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (Ecuador)", "value"=>"ES-EC", "data-type"=>"voice", "data-shorten"=>"es-EC" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (El Salvador)", "value"=>"ES-SV", "data-type"=>"voice", "data-shorten"=>"es-SV" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (Guatemala)", "value"=>"ES-GT", "data-type"=>"voice", "data-shorten"=>"es-GT" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (Honduras)", "value"=>"ES-HN", "data-type"=>"voice", "data-shorten"=>"es-HN" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (Mexico)", "value"=>"ES-MX", "data-type"=>"voice", "data-shorten"=>"es-MX" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (Nicaragua)", "value"=>"ES-NI", "data-type"=>"voice", "data-shorten"=>"es-NI" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (Panama)", "value"=>"ES-PA", "data-type"=>"voice", "data-shorten"=>"es-PA" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (Paraguay)", "value"=>"ES-PY", "data-type"=>"voice", "data-shorten"=>"es-PY" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (Peru)", "value"=>"ES-PE", "data-type"=>"voice", "data-shorten"=>"es-PE" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (Puerto Rico)", "value"=>"ES-PR", "data-type"=>"voice", "data-shorten"=>"es-PR" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (Spain)", "value"=>"ES-ES", "data-type"=>"voice", "data-shorten"=>"es-ES" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (United States)", "value"=>"ES-US", "data-type"=>"voice", "data-shorten"=>"es-US" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (United States)", "value"=>"ES-US", "data-type"=>"voice", "data-shorten"=>"es-US" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (Uruguay)", "value"=>"ES-UY", "data-type"=>"voice", "data-shorten"=>"es-UY" , "data-model"=>"command_and_search"],
            ["label"=>"Spanish (Venezuela)", "value"=>"ES-VE", "data-type"=>"voice", "data-shorten"=>"es-VE" , "data-model"=>"command_and_search"],
            ["label"=>"Sundanese (Indonesia)", "value"=>"SU-ID", "data-type"=>"voice", "data-shorten"=>"su-ID" , "data-model"=>"command_and_search"],
            ["label"=>"Swahili (Kenya)", "value"=>"SW-KE", "data-type"=>"voice", "data-shorten"=>"sw-KE" , "data-model"=>"command_and_search"],
            ["label"=>"Swahili (Tanzania)", "value"=>"SW-TZ", "data-type"=>"voice", "data-shorten"=>"sw-TZ" , "data-model"=>"command_and_search"],
            ["label"=>"Swedish (Sweden)", "value"=>"SV-SE", "data-type"=>"voice", "data-shorten"=>"sv-SE" , "data-model"=>"command_and_search"],
            ["label"=>"Tamil (India)", "value"=>"TA-IN", "data-type"=>"voice", "data-shorten"=>"ta-IN" , "data-model"=>"command_and_search"],
            ["label"=>"Tamil (Malaysia)", "value"=>"TA-MY", "data-type"=>"voice", "data-shorten"=>"ta-MY" , "data-model"=>"command_and_search"],
            ["label"=>"Tamil (Singapore)", "value"=>"TA-SG", "data-type"=>"voice", "data-shorten"=>"ta-SG" , "data-model"=>"command_and_search"],
            ["label"=>"Tamil (Sri Lanka)", "value"=>"TA-LK", "data-type"=>"voice", "data-shorten"=>"ta-LK" , "data-model"=>"command_and_search"],
            ["label"=>"Telugu (India)", "value"=>"TE-IN", "data-type"=>"voice", "data-shorten"=>"te-IN" , "data-model"=>"command_and_search"],
            ["label"=>"Thai (Thailand)", "value"=>"TH-TH", "data-type"=>"voice", "data-shorten"=>"th-TH" , "data-model"=>"command_and_search"],
            ["label"=>"Turkish (Turkey)", "value"=>"TR-TR", "data-type"=>"voice", "data-shorten"=>"tr-TR" , "data-model"=>"command_and_search"],
            ["label"=>"Ukrainian (Ukraine)", "value"=>"UK-UA", "data-type"=>"voice", "data-shorten"=>"uk-UA" , "data-model"=>"command_and_search"],
            ["label"=>"Urdu (India)", "value"=>"UR-IN", "data-type"=>"voice", "data-shorten"=>"ur-IN" , "data-model"=>"command_and_search"],
            ["label"=>"Urdu (Pakistan)", "value"=>"UR-PK", "data-type"=>"voice", "data-shorten"=>"ur-PK" , "data-model"=>"command_and_search"],
            ["label"=>"Uzbek (Uzbekistan)", "value"=>"UZ-UZ", "data-type"=>"voice", "data-shorten"=>"uz-UZ" , "data-model"=>"command_and_search"],
            ["label"=>"Vietnamese (Vietnam)", "value"=>"VI-VN", "data-type"=>"voice", "data-shorten"=>"vi-VN" , "data-model"=>"command_and_search"],
            ["label"=>"Zulu (South Africa)", "value"=>"ZU-ZA", "data-type"=>"voice", "data-shorten"=>"zu-ZA" , "data-model"=>"command_and_search"],
                        
            //For Sign
            [ "label"=>"Indo-Pakistani Sign","value"=>"LS-IPSL", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"Indonesian Sign","value"=>"LS-BISINDO", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"Russian Sign","value"=>"LS-RUS", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"Brazilian Sign","value"=>"LS-BRA", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"Spanish Sign","value"=>"LS-SPA", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"Egyptian Sign","value"=>"LS-EGY", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"American Sign","value"=>"LS-AME", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"Persian Sign","value"=>"LS-PER", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"Turkish Sign","value"=>"LS-TUR", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"Japanese Sign","value"=>"LS-JAP", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"Mexican Sign","value"=>"LS-MEX", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"French Sign","value"=>"LS-FRE", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"British Sign","value"=>"LS-BRI", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"German Sign","value"=>"LS-GER", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"Malaysian Sign","value"=>"LS-MAL", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"Polish Sign","value"=>"LS-POL", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"Italian Sign","value"=>"LS-ITA", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"Yugoslav Sign","value"=>"LS-YUG", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"Uruguayan Sign","value"=>"LS-URU", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"Hong Kong Sign","value"=>"LS-HON", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"Dutch Sign","value"=>"LS-DUT", "data-shorten"=>"", "data-type"=>"sign"],
            [ "label"=>"Auslan","value"=>"LS-AUS", "data-shorten"=>"", "data-type"=>"sign"],
        ];

        $listkeyasvalue = [];
        
        foreach($list as $lkey=>$lvalue){
            $listkeyasvalue[$lvalue["value"]] = $lvalue;
        }


?>
